package com.sngular.formacion.mobile;

import org.junit.Test;

import com.sngular.formacion.mobile.dto.Mobile;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.assertThat;

public class MobileRESTControllerTest {

	@Test
	public void whenCreate_returnsAutogeneratedId() {
		//given
		MobileRESTController controller = new MobileRESTController();
		Mobile testMobile = new Mobile()
								.setName("IPhone 6S")
								.setDesc("Super cool mobile")
								.setPrice(749.0);
		
		//when
		Mobile result = controller.create(testMobile);
		
		//then
		assertThat(result.getId(), notNullValue());
	}
}
